from __future__ import annotations

import json
from typing import Any

from rulebook.model import Rulebook

SCHEMA_VERSION = 1
SWIFT_PATH = "Sources/AppStoreReviewKit/Rulebook/Generated/EmbeddedRulebook.swift"
RAW_DELIMITER = '"""###'


def compile_rulebook(rulebook: Rulebook) -> str:
    payload: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "guidelines_revision": rulebook.guidelines_revision,
        "rules": [rule.to_json() for rule in sorted(rulebook.rules, key=lambda r: r.id)],
        "catalogs": rulebook.catalogs,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, default=str) + "\n"


def compile_swift(rulebook: Rulebook) -> str:
    json_text = compile_rulebook(rulebook)
    if RAW_DELIMITER in json_text:
        raise ValueError("The rulebook contains the Swift raw string delimiter")
    return (
        "// Generated by `uv run rulebook build`. Do not edit.\n"
        "enum EmbeddedRulebook {\n"
        '    static let json = ###"""\n'
        f"{json_text}"
        f"{RAW_DELIMITER}\n"
        "}\n"
    )
