from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from typing import Any

from rulebook.model import Automation, Rule, Rulebook

LEVEL_ORDER = (Automation.AUTOMATED, Automation.ASSISTED, Automation.MANUAL)


@dataclass(frozen=True)
class Row:
    slug: str
    label: str
    rules: tuple[Rule, ...]
    omitted: bool
    covered_by_subsections: bool = False

    @property
    def level(self) -> str:
        if self.omitted:
            return "n/a"
        if not self.rules:
            return "subsections" if self.covered_by_subsections else "uncovered"
        return min((rule.automation for rule in self.rules), key=LEVEL_ORDER.index).value


def rows(rulebook: Rulebook) -> list[Row]:
    by_section: dict[str, list[Rule]] = defaultdict(list)
    for rule in rulebook.rules:
        for section in rule.guidelines:
            by_section[section].append(rule)
    sections = rulebook.guideline_sections

    def has_rules_below(slug: str) -> bool:
        children = sections.get(slug, {}).get("children", [])
        return any(by_section[child] or has_rules_below(child) for child in children)

    return [
        Row(
            slug=slug,
            label=_label(section),
            rules=tuple(sorted(by_section[slug], key=lambda r: r.id)),
            omitted=section.get("omitted", False),
            covered_by_subsections=has_rules_below(slug),
        )
        for slug, section in sections.items()
        if "." in (section.get("number") or "")
    ]


def render(rulebook: Rulebook) -> str:
    table = rows(rulebook)
    counts: dict[str, int] = defaultdict(int)
    for row in table:
        counts[row.level] += 1
    rule_counts: dict[str, int] = defaultdict(int)
    for rule in rulebook.rules:
        rule_counts[rule.automation.value] += 1

    lines = [
        "# Coverage",
        "",
        "Every numbered guideline of the App Review Guidelines "
        f"(revision {rulebook.guidelines_revision}) against the rules that cover it. "
        "Generated by `uv run rulebook coverage`; do not edit by hand.",
        "",
        "A section's level is the strongest automation among its rules: "
        "**automated** needs no human, **assisted** finds evidence and asks a human to judge it, "
        "**manual** is a review question only, "
        "**subsections** is a heading whose subsections hold the rules, "
        "**uncovered** has no rule yet.",
        "",
        "## Summary",
        "",
        "| Level | Sections | Rules |",
        "| --- | --- | --- |",
    ]
    for level in ("automated", "assisted", "manual", "subsections", "uncovered", "n/a"):
        rule_count = str(rule_counts[level]) if level in rule_counts else "-"
        lines.append(f"| {level} | {counts[level]} | {rule_count} |")
    lines += [
        "",
        f"{len(rulebook.rules)} rules in total, including ones enforced by upload validation "
        "or App Store Connect rather than a guideline section.",
        "",
        "## Sections",
        "",
        "| Section | Level | Rules |",
        "| --- | --- | --- |",
    ]
    for row in table:
        rules = ", ".join(f"`{rule.id}`" for rule in row.rules) or "-"
        link = f"[{row.label}](guidelines/{row.slug}.md)"
        lines.append(f"| {link} | {row.level} | {rules} |")
    return "\n".join(lines) + "\n"


def _label(section: dict[str, Any]) -> str:
    title = section.get("title") or ""
    return f"{section['number']} {title}".strip().replace("|", "\\|")
